FROM node:20-alpine AS build

WORKDIR /app

COPY package.json .
COPY package-lock.json .

RUN npm install

COPY . .

RUN npm run build

# --- Segunda etapa: Nginx ---

FROM nginx:alpine

# 1. Copia el archivo de configuración de Nginx creado en el Paso 1
#    Esto reemplaza la configuración por defecto de Nginx
COPY nginx.conf /etc/nginx/conf.d/default.conf

# 2. Copia los archivos de build de React
COPY --from=build /app/dist /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]