# Generated by Django 4.2.10 on 2025-10-16 19:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('paciente', '0003_logeliminacionpaciente'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('motivo_consulta', models.TextField()),
                ('estado_cita', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('COMPLETA', 'Completa'), ('AUSENCIA', 'Ausencia'), ('CANCELADA', 'Cancelada')], default='PENDIENTE', max_length=10)),
                ('justificacion_ausencia', models.TextField(blank=True, null=True)),
                ('dolor_localizacion', models.CharField(blank=True, max_length=100, null=True)),
                ('procedimiento', models.TextField(blank=True, null=True)),
                ('pulso_bpm', models.FloatField(blank=True, null=True)),
                ('oxigeno_spo2', models.FloatField(blank=True, null=True)),
                ('peso_kg', models.FloatField(blank=True, null=True)),
                ('altura_cm', models.FloatField(blank=True, null=True)),
                ('presion_sistolica', models.FloatField(blank=True, null=True)),
                ('presion_diastolica', models.FloatField(blank=True, null=True)),
                ('glicemia', models.FloatField(blank=True, null=True)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paciente.paciente')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Terapia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CitaTerapia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_cita', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cita.cita')),
                ('id_terapia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cita.terapia')),
            ],
        ),
    ]
