# Generated by Django 4.2.10 on 2025-10-16 21:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cita', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cita',
            name='altura_cm',
        ),
        migrations.RemoveField(
            model_name='cita',
            name='dolor_localizacion',
        ),
        migrations.RemoveField(
            model_name='cita',
            name='glicemia',
        ),
        migrations.RemoveField(
            model_name='cita',
            name='oxigeno_spo2',
        ),
        migrations.RemoveField(
            model_name='cita',
            name='peso_kg',
        ),
        migrations.RemoveField(
            model_name='cita',
            name='presion_diastolica',
        ),
        migrations.RemoveField(
            model_name='cita',
            name='presion_sistolica',
        ),
        migrations.RemoveField(
            model_name='cita',
            name='procedimiento',
        ),
        migrations.RemoveField(
            model_name='cita',
            name='pulso_bpm',
        ),
        migrations.CreateModel(
            name='AtencionCita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dolor_localizacion', models.CharField(blank=True, max_length=100, null=True)),
                ('procedimiento', models.TextField(blank=True, null=True)),
                ('pulso_bpm', models.FloatField(blank=True, null=True)),
                ('oxigeno_spo2', models.FloatField(blank=True, null=True)),
                ('peso_kg', models.FloatField(blank=True, null=True)),
                ('altura_cm', models.FloatField(blank=True, null=True)),
                ('presion_sistolica', models.FloatField(blank=True, null=True)),
                ('presion_diastolica', models.FloatField(blank=True, null=True)),
                ('glicemia', models.FloatField(blank=True, null=True)),
                ('cita', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='atencion', to='cita.cita')),
            ],
        ),
        migrations.AlterField(
            model_name='citaterapia',
            name='id_cita',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cita.atencioncita'),
        ),
    ]
