# Generated by Django 4.2.10 on 2025-10-16 22:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cita', '0002_remove_cita_altura_cm_remove_cita_dolor_localizacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citaterapia',
            name='id_terapia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='terapias_aplicadas', to='cita.atencioncita'),
        ),
    ]
