# Generated by Django 4.2.10 on 2025-10-16 22:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cita', '0003_alter_citaterapia_id_terapia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citaterapia',
            name='id_cita',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='terapias_aplicadas', to='cita.atencioncita'),
        ),
        migrations.AlterField(
            model_name='citaterapia',
            name='id_terapia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cita.terapia'),
        ),
    ]
