# Generated by Django 4.2.10 on 2025-10-20 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cita', '0004_alter_citaterapia_id_cita_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='es_grupal',
            field=models.BooleanField(default=False),
        ),
    ]
