# Generated by Django 4.2.10 on 2025-10-16 02:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pruebas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resultadoprueba',
            name='resultado',
        ),
        migrations.AddField(
            model_name='resultadoprueba',
            name='observaciones',
            field=models.TextField(blank=True, help_text='Observaciones generales del terapeuta', null=True),
        ),
        migrations.AddField(
            model_name='resultadoprueba',
            name='puntuacion_total',
            field=models.IntegerField(blank=True, help_text='Puntaje final calculado para el test', null=True),
        ),
        migrations.AlterField(
            model_name='respuesta',
            name='pregunta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuestas_dadas', to='pruebas.pregunta'),
        ),
        migrations.AlterField(
            model_name='resultadoprueba',
            name='fecha_evaluacion',
            field=models.DateField(auto_now_add=True),
        ),
    ]
