# Generated by Django 4.2.10 on 2025-11-05 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporte', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reporte',
            name='evaluaciones_realizadas',
            field=models.TextField(blank=True, null=True),
        ),
    ]
