# Generated by Django 4.2.10 on 2025-11-18 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporte', '0002_reporte_evaluaciones_realizadas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reporte',
            name='comentarios',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='reporte',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reporte',
            name='evaluaciones_realizadas',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
