# Generated by Django 4.2.10 on 2025-10-14 05:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Epicrisis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(upload_to='epicrisis_fotos/')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(max_length=100)),
                ('cedula', models.CharField(max_length=20, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('telefono', models.CharField(blank=True, max_length=15, null=True)),
                ('genero', models.CharField(choices=[('Masculino', 'Masculino'), ('Femenino', 'Femenino'), ('Otro', 'Otro')], default='Otro', max_length=10)),
                ('fecha_nacimiento', models.DateField()),
                ('fecha_ingreso', models.DateTimeField(auto_now_add=True)),
                ('enfermedades', models.TextField(blank=True, null=True)),
                ('estado_pension', models.CharField(blank=True, max_length=50, null=True)),
                ('monto_pension', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('personas_con_las_que_habita', models.TextField(blank=True, null=True)),
                ('tiene_diabetes', models.BooleanField(default=False)),
                ('fecha_diagnostico_diabetes', models.DateField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('direccion', models.CharField(blank=True, max_length=255, null=True)),
                ('esta_activo', models.BooleanField(default=True)),
                ('foto_epicrisis', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pacientes_con_foto', to='paciente.epicrisis')),
            ],
        ),
        migrations.AddField(
            model_name='epicrisis',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='epicrisis_fotos', to='paciente.paciente'),
        ),
    ]
