# Generated by Django 4.2.10 on 2025-10-14 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paciente',
            name='foto_epicrisis',
        ),
        migrations.AddField(
            model_name='paciente',
            name='cantidad_hijos',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='paciente',
            name='profesion',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='fecha_ingreso',
            field=models.DateField(auto_now_add=True),
        ),
    ]
